#spring:
#  jpa:
#   hibernate:
#    ddl-auto: update
#    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#  datasource:
#    url: "jdbc:mysql://us-cdbr-east-06.cleardb.net/heroku_c573fe4ac351ebd"
#    username: b2b8a0ba8285db
#    password: 29229c19
#    hikari:
#      max-lifetime: 20000


url: jdbc:postgresql://localhost:5432/test

dialect:  org.hibernate.dialect.PostgreSQLDialect

sql:
  init:
    mode: always

  password: robeilaregawi
  username: postgres
  url: jdbc:postgresql://localhost:5432/portfolio_db