#spring:
#  jpa:
#   hibernate:
#    ddl-auto: update
#    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#  datasource:
#    url: "jdbc:mysql://us-cdbr-east-06.cleardb.net/heroku_c573fe4ac351ebd"
#    username: b2b8a0ba8285db
#    password: 29229c19
#    hikari:
#      max-lifetime: 20000